const team_data = `{
    "api": {
        "results": 19,
        "teams": [
            {
                "team_id": 2291,
                "name": "Puebla",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2291.png",
                "country": "Mexico",
                "founded": 1944,
                "venue_name": "Estadio Cuauhtémoc",
                "venue_surface": "grass",
                "venue_address": "Calle Calzada Ignacio Zaragoza, Colonia Unidad Deportiva Puebla",
                "venue_city": "Puebla",
                "venue_capacity": 51726
            },
            {
                "team_id": 2280,
                "name": "Club Tijuana",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2280.png",
                "country": "Mexico",
                "founded": 2006,
                "venue_name": "Estadio Caliente",
                "venue_surface": "artificial turf",
                "venue_address": "Boulevard Agua Caliente 12027, Colonia Hipódromo",
                "venue_city": "Tijuana",
                "venue_capacity": 29333
            },
            {
                "team_id": 2283,
                "name": "Atlas",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2283.png",
                "country": "Mexico",
                "founded": 1916,
                "venue_name": "Estadio Jalisco",
                "venue_surface": "grass",
                "venue_address": "Calle 7 Colinas No. 1772, Colonia Independencia",
                "venue_city": "Guadalajara",
                "venue_capacity": 56713
            },
            {
                "team_id": 2298,
                "name": "FC Juarez",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2298.png",
                "country": "Mexico",
                "founded": 2015,
                "venue_name": "Estadio Olímpico Benito Juárez",
                "venue_surface": "grass",
                "venue_address": "Avenida Heroico Colegio Militar",
                "venue_city": "Ciudad Juárez",
                "venue_capacity": 22300
            },
            {
                "team_id": 2314,
                "name": "Atletico San Luis",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2314.png",
                "country": "Mexico",
                "founded": 2013,
                "venue_name": "Estadio Alfonso Lastras Ramírez",
                "venue_surface": "grass",
                "venue_address": "Avenida Malaquita 1030",
                "venue_city": "San Luis Potosí",
                "venue_capacity": 26400
            },
            {
                "team_id": 2286,
                "name": "U.N.A.M. - Pumas",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2286.png",
                "country": "Mexico",
                "founded": 1954,
                "venue_name": "Estadio Olímpico de Universitario",
                "venue_surface": "grass",
                "venue_address": "Calle Escobar, Colonia Ciudad Universitaria, Coyoacán",
                "venue_city": "D.F.",
                "venue_capacity": 72449
            },
            {
                "team_id": 2292,
                "name": "Pachuca",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2292.png",
                "country": "Mexico",
                "founded": 1901,
                "venue_name": "Estadio Hidalgo",
                "venue_surface": "grass",
                "venue_address": "Boulevard Felipe Angeles",
                "venue_city": "Pachuca de Soto",
                "venue_capacity": 30000
            },
            {
                "team_id": 2289,
                "name": "Leon",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2289.png",
                "country": "Mexico",
                "founded": 1944,
                "venue_name": "Estadio León (Nou Camp)",
                "venue_surface": "grass",
                "venue_address": "Boulevard Adolfo López Mateos 1810, Colonia La Martinica",
                "venue_city": "León de los Aldamas",
                "venue_capacity": 33943
            },
            {
                "team_id": 2279,
                "name": "Tigres UANL",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2279.png",
                "country": "Mexico",
                "founded": 1960,
                "venue_name": "Estadio Universitario de Nuevo León",
                "venue_surface": "grass",
                "venue_address": "Calle del Doctor Pedro de Alba, Colonia Ciudad Universitaria",
                "venue_city": "San Nicolás de los Garza",
                "venue_capacity": 42000
            },
            {
                "team_id": 2284,
                "name": "Monarcas",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2284.png",
                "country": "Mexico",
                "founded": 1920,
                "venue_name": "Estadio Generalísimo José María Morelos y Pavón",
                "venue_surface": "grass",
                "venue_address": "Libramiento Norte, Colonia Leandro Valle",
                "venue_city": "Morelia",
                "venue_capacity": 41056
            },
            {
                "team_id": 2287,
                "name": "Club America",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2287.png",
                "country": "Mexico",
                "founded": 1916,
                "venue_name": "Estadio Azteca",
                "venue_surface": "grass",
                "venue_address": "Calzada de Tlalpan 3665, Coyoacán",
                "venue_city": "D.F.",
                "venue_capacity": 106187
            },
            {
                "team_id": 2282,
                "name": "Monterrey",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2282.png",
                "country": "Mexico",
                "founded": 1945,
                "venue_name": "Estadio BBVA Bancomer",
                "venue_surface": "grass",
                "venue_address": "Avenida Pablo Livas 2011, Colonia La Pastora",
                "venue_city": "Guadalupe",
                "venue_capacity": 53500
            },
            {
                "team_id": 2288,
                "name": "Necaxa",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2288.png",
                "country": "Mexico",
                "founded": 1923,
                "venue_name": "Estadio Victoria de Aguascalientes",
                "venue_surface": "grass",
                "venue_address": "Avenida Manuel Madrigal 101, Colonia Héroes",
                "venue_city": "Aguascalientes",
                "venue_capacity": 25500
            },
            {
                "team_id": 2295,
                "name": "Cruz Azul",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2295.png",
                "country": "Mexico",
                "founded": 1927,
                "venue_name": "Estadio Azteca",
                "venue_surface": "grass",
                "venue_address": "Calzada de Tlalpan 3665, Coyoacán",
                "venue_city": "D.F.",
                "venue_capacity": 106187
            },
            {
                "team_id": 2281,
                "name": "Toluca",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2281.png",
                "country": "Mexico",
                "founded": 1917,
                "venue_name": "Estadio Nemesio Díez",
                "venue_surface": "grass",
                "venue_address": "Avenida Constituyentes Poniente No. 1000, Colonia La Merced",
                "venue_city": "Toluca de Lerdo",
                "venue_capacity": 30000
            },
            {
                "team_id": 2290,
                "name": "Club Queretaro",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2290.png",
                "country": "Mexico",
                "founded": 1950,
                "venue_name": "Estadio La Corregidora",
                "venue_surface": "grass",
                "venue_address": "Avenida Luis Vega Monroy 409-4",
                "venue_city": "Santiago de Querétaro",
                "venue_capacity": 34130
            },
            {
                "team_id": 2285,
                "name": "Santos Laguna",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2285.png",
                "country": "Mexico",
                "founded": 1983,
                "venue_name": "Estadio Nuevo Corona",
                "venue_surface": "grass",
                "venue_address": "Territorio Santos Modelo",
                "venue_city": "Torreón",
                "venue_capacity": 28914
            },
            {
                "team_id": 2278,
                "name": "Guadalajara Chivas",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2278.png",
                "country": "Mexico",
                "founded": 1906,
                "venue_name": "Estadio AKRON",
                "venue_surface": "artificial turf",
                "venue_address": "Avenida Circuito JVC Número 2800, Centro JVC",
                "venue_city": "Zapopan",
                "venue_capacity": 46609
            },
            {
                "team_id": 2294,
                "name": "Veracruz",
                "code": null,
                "logo": "https:\/\/www.api-football.com\/public\/teams\/2294.png",
                "country": "Mexico",
                "founded": 1943,
                "venue_name": "Estadio Luis de la Fuente",
                "venue_surface": "grass",
                "venue_address": "Paseo Jacarandas y Paseo Jardín, Fracc. Virginia, Colonia Boca del Río",
                "venue_city": "Veracruz",
                "venue_capacity": 26316
            }
        ]
    }
}`;